### ISSUE TITLE
[GAME] `java.lang.ArithmeticException` (divide by zero) in `Animation::nextAnimationTexturePath`

### ISSUE THREAD

**Issue by malt-r** [Programmiermethoden/Dungeon#1241]
Tritt seit https://github.com/Programmiermethoden/Dungeon/pull/1236 auf.

Stacktrace:
```
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at core.utils.components.draw.Animation.nextAnimationTexturePath(Animation.java:186)
	at core.systems.DrawSystem.draw(DrawSystem.java:84)
	at core.systems.DrawSystem.lambda$execute$1(DrawSystem.java:76)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at core.systems.DrawSystem.execute(DrawSystem.java:76)
	at core.game.GameLoop.render(GameLoop.java:145)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at core.game.GameLoop.run(GameLoop.java:97)
	at core.Game.run(Game.java:41)
	at starter.Starter.main(Starter.java:130)
```

Repro-Steps:
- Dungeon mit `gradle start --args "dungeon/assets/scripts/internal_scenario_builder_usage.dng"` starten
- Raum mit dem `AssignTask` betreten, in dem Schriftrollen auf dem Boden liegen

Erklärung:
Im nativen Szenariobuilder für einen `AssignTask` werden Schriftrollen-Items mit folgendem Snippet erstellt:
``` java
Animation animation =
  Animation.fromSingleImage(
    new SimpleIPath("items/book/wisdom_scroll.png"),
    CoreAnimationPriorities.DEFAULT.priority());
TaskContentComponent tcc = new TaskContentComponent(element);
QuestItem questItem = new QuestItem(animation, tcc);
Entity worldItem = WorldItemBuilder.buildWorldItem(questItem);
roomSet.add(worldItem);
```

In den `Animation::nextAnimationTexturePath` Aufrufen für diese `Entity`s dieser Items tritt beschriebene Exception auf, weil `timeBetweenFrames` `0` ist.

**Comment by AHeinisch** [comment]
Fehler gefunden. Wir hatten einen ctor(String bild, int prio) und eine factory(String bild, int frames)
