### ISSUE TITLE
[GAME] fix GameTest Tests 

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#445]
Die Tests in `starter/GameTest` schlagen fehl (obwohl die Funktionalität gegeben zu sein scheint).
In den Tests wird Mockito und PowerMock verwendet. Vielleicht liegt hier das Problem.

Es muss sich jemand die Tests anschauen und reparieren. Wenn dabei PowerMock und/oder Mockito rausfliegen, um so besser.

Vor allem **PowerMock** darf gern rausfliegen - das wird scheinbar nicht mehr verlässlich maintained.

#Time:2

**Comment by cagix** [comment]
Vor allem **PowerMock** darf gern rausfliegen - das wird scheinbar nicht mehr verlässlich maintained!

**Comment by JudiTeller** [comment]
aktuell gefundene Probleme

- [ ] Erstellen eines Loggers in Game Klasse
- [ ] Erstellen eines PauseMenu in Game Klasse
(- [ ] Aufruf von statischen Methoden (Aufrufkaskade beginnt in spy der Game Klasse))
- [ ] Erstellen des Heros im spy Game::setup() findet keine texturen (returned null, womöglich durch Aufruf einer statischen Methode)

Wenn die Punkte vorsichtig aus der Game-Klasse auskommentiert werden, läuft der Test erfolgreich durch.

Der Logger bedingt folgenden trace:
```java
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private void java.util.logging.Logger.checkPermission() throws java.lang.SecurityException accessible: module java.logging does not "opens java.util.logging" to unnamed module @333291e3
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.powermock.reflect.internal.WhiteboxImpl.doGetAllMethods(WhiteboxImpl.java:1508)
	at org.powermock.reflect.internal.WhiteboxImpl.getAllMethods(WhiteboxImpl.java:1482)
	at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1750)
	at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1789)
	at org.powermock.reflect.internal.WhiteboxImpl.getBestMethodCandidate(WhiteboxImpl.java:1008)
	at org.powermock.core.MockInvocation.findMethodToInvoke(MockInvocation.java:58)
	at org.powermock.core.MockInvocation.init(MockInvocation.java:35)
	at org.powermock.core.MockInvocation.<init>(MockInvocation.java:22)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:155)
	at org.powermock.core.MockGateway.methodCall(MockGateway.java:138)
	at starter.Game.<init>(Game.java:74)
	at starter.Game$MockitoMock$755524788.<init>(Unknown Source)
	... 62 more 
```
Pause Menu bedingt diesen:
```java
java.lang.UnsatisfiedLinkError: 'java.nio.ByteBuffer com.badlogic.gdx.utils.BufferUtils.newDisposableByteBuffer(int)'
	at com.badlogic.gdx.utils.BufferUtils.newDisposableByteBuffer(Native Method)
	at com.badlogic.gdx.utils.BufferUtils.newUnsafeByteBuffer(BufferUtils.java:519)
	at com.badlogic.gdx.graphics.glutils.VertexArray.<init>(VertexArray.java:59)
	at com.badlogic.gdx.graphics.Mesh.<init>(Mesh.java:189)
	at com.badlogic.gdx.graphics.Mesh.<init>(Mesh.java:160)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:104)
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:81)
	at graphic.hud.PauseMenu.<init>(PauseMenu.java:15)
	at starter.Game.setup(Game.java:87)
	at starter.Game.firstFrame(Game.java:159)
	at starter.Game.render(Game.java:129)
	at starter.GameTest.test_render(GameTest.java:61)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```
Erstellen Hero:
```java
java.lang.ExceptionInInitializerError
	at dslToGame.AnimationBuilder.buildAnimation(AnimationBuilder.java:12)
	at ecs.entities.Hero.setupAnimationComponent(Hero.java:52)
	at ecs.entities.Hero.<init>(Hero.java:48)
	at starter.Game.setup(Game.java:89)
	at starter.Game.firstFrame(Game.java:159)
	at starter.Game.render(Game.java:129)
	at starter.GameTest.test_render(GameTest.java:61)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.NullPointerException: Cannot invoke "com.badlogic.gdx.Files.getLocalStoragePath()" because "com.badlogic.gdx.Gdx.files" is null
	at graphic.textures.TextureHandler.<init>(TextureHandler.java:26)
	at graphic.textures.TextureHandler.<clinit>(TextureHandler.java:21)
	at dslToGame.AnimationBuilder.buildAnimation(AnimationBuilder.java:12)
	at ecs.entities.Hero.setupAnimationComponent(Hero.java:52)
	at ecs.entities.Hero.<init>(Hero.java:48)
	at starter.Game.setup(Game.java:89)
	at starter.Game$MockitoMock$191358823.setup$accessor$ibumqZ9Q(Unknown Source)
	at starter.Game$MockitoMock$191358823$auxiliary$6PZgNbnt.call(Unknown Source)
	at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
	at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:152)
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
	at org.mockito.Answers.answer(Answers.java:100)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:61)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:108)
	at starter.Game$MockitoMock$191358823.setup(Unknown Source)
	at starter.Game.firstFrame(Game.java:159)
	at starter.Game.render(Game.java:129)
	at starter.Game$MockitoMock$191358823.render$accessor$ibumqZ9Q(Unknown Source)
	at starter.Game$MockitoMock$191358823$auxiliary$7qvJC3f0.call(Unknown Source)
	at org.mockito.internal.invocation.RealMethod$FromCallable$1.call(RealMethod.java:40)
	at org.mockito.internal.invocation.RealMethod$FromBehavior.invoke(RealMethod.java:62)
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:152)
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:44)
	at org.mockito.Answers.answer(Answers.java:100)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:61)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:49)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:108)
	at starter.Game$MockitoMock$191358823.render(Unknown Source)
	at starter.GameTest.test_render(GameTest.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:89)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:97)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:117)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	... 9 more
```

nächster Schritt ist da durchzuschauen, wie man das lösen kann.

**Comment by JudiTeller** [comment]
das Problem des Loggers konnte ich doch fixen ohne auf ein anderes Loggermodul umzusteigen
dazu musste der access zur Loggerklasse spezifisch für die Tests erweitert werden

```
The "java.lang.reflect.InaccessibleObjectException" is a Java error that occurs when
you are trying to access a private method or field of a class from outside the class,
and you don't have the necessary permissions to access it.```

gemacht durch mitgabe eines jvm Arguments in der build.gradle

**Comment by JudiTeller** [comment]
Der Fehler bzgl. des PauseMenu scheint dadurch zu entstehen, dass die Testumgebung die Methode
`com.badlogic.gdx.utils.BufferUtils.newDisposableByteBuffer(int)`
nicht findet.
Gerade noch am Suchen, warum die libgdx library nicht geladen wird, warum das nur bei den JUnit Tests vorkommt und wie man das beheben kann.

**Comment by JudiTeller** [comment]
PauseMenu Problem gelöst durch spezifisches Einbinden der libgdx natives in GameTest::setup() per GdxNativesLoader.load()

**Comment by JudiTeller** [comment]
Der obenstehende Error beim Erstellen des Heroes innerhalb der Testsuite wird auch behoben und durch einen neuen Error ersetzt, sobald Gdx komplett initialisiert wird.
Ich denke, der sinnvollste Ansatz ist hier erst die Initialisierung zu erlauben und den Killswitch für Tests einzubauen, bevor tiefer gegraben wird.

**Comment by JudiTeller** [comment]
@fwatermann was sagst du dazu?
Ist die Idee mit dem Killswitch überhaupt sinnvoll?
An welcher Stelle ist der am sinnvollsten?

Ich habe schon versucht den in Game::render mit einzubauen, dann wird die Methode aber mind. 2 Mal aufgerufen und der Test failed dann dadurch.
Game erhält einen boolean als Instanzvariable, die in GameTest::setup gesetzt wird
Bsp:
```java
public void render(float delta) {
        if (doFirstFrame) {
            firstFrame();
        }
        batch.setProjectionMatrix(camera.combined);

        if (junitRunning) {
            Gdx.app.exit();
        }

        if (runLoop()) {
            frame();
.
.
.
```

**Comment by JudiTeller** [comment]
@AHeinisch auch gerne mal deine Meinung, wenn du Zeit hast

**Comment by JudiTeller** [comment]
Ja genau, wollte einfach eine Einschätzung.
Ich habe nämlich das Gefühl, dass der fix zu einem immensem rabbit-hole wird :smile: 
Denke, wir besprechen das am besten einfach morgen mit Andre.

**Comment by fwatermann** [comment]
Da bin ich mit der Meinung von @AHeinisch. Wir würden dann beim Testen ja "schummeln"...
Ich gehe davon aus, dass sobald wir irgendwas mit rendering machen, also irgendwo wird ein OpenGL-Kontext benötigt, während der Tests sowieso immer Probleme haben werden.

Vielleicht gibt es von GDX eine Headless, daher ohne Calls an OpenGL, version? Die Könnte eventuell helfen 🤔

**Comment by cagix** [comment]
ohne jetzt wirklich drüber nachgedacht zu haben:

> Vielleicht ist dies eher eine komplett neue Testgruppe, wo die Anwendung gestartet wird und anhand der geschriebenen Log Datei entschieden wird, ob es gültig ist.

klingt gut.

**Comment by AMatutat** [comment]
> Vielleicht ist dies eher eine komplett neue Testgruppe, wo die Anwendung gestartet wird und anhand der geschriebenen Log Datei entschieden wird, ob es gültig ist.


Klingt wirklich gut. 
Eigenes Loglevel "Test" und dann ab der Fisch.
@cagix Ich würde @JudiTeller den Ansatz gerne über die nächsten Wochen untersuchen und vorberetien/umsetzten lassen. 
Spricht aus deiner Sicht was dagegen? 
Vielleicht erfahren wir dann auch noch etwas, dass wir im "D2G-Dungeon Nelson-Style Gedanken Konstrukt" einbinden können

**Comment by cagix** [comment]
Fisch ist gut. Habe ne neue gusseiserne Pfanne - lasst uns das Viech braten :) 

Wie sagt Picard immer? "Engage!"
