### ISSUE TITLE
[GAME] Knopfdruck "Q" lässt Spiel abstürzen

### ISSUE THREAD

**Issue by JudiTeller** [Programmiermethoden/Dungeon#488]
Wenn im laufenden Spiel die Taste "Q" gedrückt wird, kracht das gesamte Programm zusammen.
Der Knopfdruck soll Skill 1 auslösen.
Verhalten konnte von mir mit keinem anderen Knopfdruck nachgestellt werden.

Error stacktrace:
```java
Exception in thread "main" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1712)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at ecs.systems.PlayerSystem.update(PlayerSystem.java:22)
	at controller.SystemController.process(SystemController.java:19)
	at controller.SystemController.process(SystemController.java:7)
	at controller.AbstractController.update(AbstractController.java:27)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at starter.Game.render(Game.java:138)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at starter.DesktopLauncher.run(DesktopLauncher.java:26)
	at starter.Game.main(Game.java:250)
```

**Comment by JudiTeller** [comment]
ist duplikat zu #486
