### ISSUE TITLE
[GAME] AITools.getRandomAccessibleTileCoordinateInRange: IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#626]
Bekomme ab und an eine Exception geworfen die mit dem AI Verhalten in Verbindung steht.
Hab grade keine Zeit das weiter zu analysieren, daher hier mal alle Eckdaten. 

```
Exception in thread "main" java.lang.IllegalArgumentException: bound must be positive
        at java.base/java.util.Random.nextInt(Random.java:322)
        at ecs.components.ai.AITools.getRandomAccessibleTileCoordinateInRange(AITools.java:105)
        at ecs.components.ai.idle.StaticRadiusWalk.idle(StaticRadiusWalk.java:50)
        at ecs.components.ai.AIComponent.execute(AIComponent.java:49)
        at ecs.systems.AISystem.lambda$update$2(AISystem.java:17)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at ecs.systems.AISystem.update(AISystem.java:17)
        at controller.SystemController.process(SystemController.java:19)
        at controller.SystemController.process(SystemController.java:7)
        at controller.AbstractController.update(AbstractController.java:27)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at starter.Game.render(Game.java:99)
        at com.badlogic.gdx.Game.render(Game.java:48)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
        at starter.DesktopLauncher.run(DesktopLauncher.java:26)
        at starter.Game.main(Game.java:83)

```

```java
    public static Coordinate getRandomAccessibleTileCoordinateInRange(Point center, float radius) {
        List<Tile> tiles = getAccessibleTilesInRange(center, radius);
        Coordinate newPosition = tiles.get(random.nextInt(tiles.size())).getCoordinate(); /7 <- this one
        return newPosition;
    }
```

So sieht die AI meines Monster aus: 

```java
        IFightAI fightAI = new CollideAI(RANDOM.nextFloat(1.5f));
        ITransition transition = new RangeTransition(RANDOM.nextFloat(2f, 4f));
        IIdleAI idle = new StaticRadiusWalk(RANDOM.nextFloat(10f), RANDOM.nextInt(2, 4));
```

**Comment by AMatutat** [comment]
Ich meine mich zu erinner, dass das aufgetreten ist, wenn ein Monster am Levelrand lang lief. 

Wenn ich mir den Code anschaue, könnte es vielleicht auftreten, wenn `getAccessibleTilesInRange` die größe 0 hat? 
`random.nextInt(0)` sollte eine IlligalArgument werfen

```java
   public static Coordinate getRandomAccessibleTileCoordinateInRange(Point center, float radius) {
        List<Tile> tiles = getAccessibleTilesInRange(center, radius);
        Coordinate newPosition = tiles.get(random.nextInt(tiles.size())).getCoordinate(); // <- this one
        return newPosition;
    }
```

**Comment by cagix** [comment]
> Die Frage ist: Was geben wir in diesen Fall zurück? Optional?

`List<Tile> tiles = getAccessibleTilesInRange(center, radius);`

Eine leere Liste. Es muss halt vor `tiles.get()` nochmal geprüft werden, ob die Liste leer ist und anderenfalls etwas sinnvolles gemacht werden: Exception, wenn es wirklich ein Fehler ist oder eine Coordinate, die irgendwie Sinn macht (vielleicht die zu dem Parameter `center` gehörige Coordinate?).

**Comment by AMatutat** [comment]
> Edit: Oder meinst Du der Rückgabetyp der Methode selbst? 

Yep, das meine ich.

> Da würde ich zur Not genau die Koordinate zurückliefern, die mir mein Kunde gegeben hat (den Parameter center). Das Ding sollte ja auf alle Fälle accessible sein, oder?

Für meinen Geschmack impliziert mir das zu viel. Ja, im aktuellen Anwendungsfall sollte `center` auch immer Accessible sein, da wir es nur für die Berechnung der nächsten Position von der aktuellen Position aus verwenden. Aber das machen wir als User/Kunde. Die Methode sollte das nicht implizieren.

```java
   public static Optional<Coordinate> randomAccessibleTileCoordinateInRange(Point center, float radius) {
        Coordinate newPosition;
        List<Tile> tiles = getAccessibleTilesInRange(center, radius);
        if(!tiles.isEmpty()) 
            newPosition = tiles.get(random.nextInt(tiles.size())).getCoordinate(); // <- this one
        return Optional.ofNullable(newPosition);
    }
```

Das impliziert nix, ich kann an aufrufender stelle damit umgehen (z.B indem ich dann meine Position nicht ändere) und semantisch scheint mir das auch korrekter zu sein. Ich gebe dir was, und wenn es nix gibt das passt, gebe ich dir halt nix.

**Comment by cagix** [comment]
macht sinn :)
