### ISSUE TITLE
[GAME] ConcurrentModificationException wenn eine UI durch ein System erstellt wird

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#628]
Ich habe mir mal einen NPC gebaut, der bei der Kollision mit dem Helden eine Frage stellen soll. 
Bei der Kollision wurde mir eine `ConcurrentModificationException` geworfen.
Nach einem kurzen Blick in den Code scheint mir das gleiche Problem wie bei den Entitäten damals zu sein.

Aus `UITools#generateQuizDialogue`: 
```java
Game.controller.add(
                    new ResponsiveDialogue(
                            new SpriteBatch(),
                            new Skin(Gdx.files.internal(Constants.SKIN_FOR_DIALOG)),
                            Color.WHITE,
                            question,
                            arrayOfMessages))
```

In meinem konkreten Szenario wird also über alle `Controller` in `Game.controller` iteriert (damit auch über die Systeme, die da mit drinstecken) und das `HitboxSystem` ruft dann `UITools#generateQuizDialogue` auf, was mir einen neuen Controller in `Game.controller` steckt => 

Stacktrace:
Exception in thread "main" java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1513)
        at starter.Game.render(Game.java:100)
        at com.badlogic.gdx.Game.render(Game.java:48)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
        at starter.DesktopLauncher.run(DesktopLauncher.java:26)
        at starter.Game.main(Game.java:84)
```
Ich denke, die Lösung wird auch hier sein, mit einer `toAdd` Collection zu arbeiten und zwischen den Iterationen über die Controller das Ganze dann hinzuzufügen. 
Wir sollten aber auch #550 bedenken.

**Comment by AHeinisch** [comment]
Dieses Problem entfällt, da wir keine Systeme mehr haben, welche hinzugefügt werden.
